name: "CODE Server"
description: "A Collabora Online Development server for Nextcloud/ownCloud"
version: "1.0.0"
slug: "codeserver"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386